print(" you are my sunshine !")
print("my only sunshine !")
print("you make me happy !")
print("when skies are gray !")
print("you'll never know dear !")
print("how much i love you !")
print("please don't take my sunshine away !")
print(" you are my sundhine !")