CREATE TABLE IF NOT EXIST NOBEL_WIN (
    YEAR INTIGER,
    SUBJECT TEXT,
    WINNER TEXT,
    COUNTRY TEXT,
    CATEGORY TEXT
);

INSERT INTO NOBEL_WIN (YEAR, SUBJECT, WINNER, COUNRY, CATEGORY) VALUES
  (1970, 'PHYSICS', 'HANNES ALFVEN', 'SWEDEN' 'SCIENTIST'),
  (1970, 'PHYSICS', 'LUIS NEEL', 'FRANCE' 'SCIENTIST'),
  (1971, 'PHYSICS', 'PAUL', 'FRANE' 'SCIENTIST'),
  (1971, 'CHEMISTRY', 'HAMITON', 'GERMANY' 'LIGUIST'),
  (1972, 'LITERATURE', 'BERNARD KELSON', 'SWEDEN' 'ECONOMIST'),
  (1972, 'ECONOMICS', 'JOSEPH', 'GERMANY' 'ECONOMIST'),
  (1973, 'BIOLOGY', 'PHILIPS', 'RUSSA' 'PRIME MINISTER'),
  (1980, 'biology', 'MARTIN', 'HUNGARY' 'PRESIDENT'),
  (1981, 'PHYSIOLOGY', 'HANNAN', 'CHILLY' 'SCIENTIST'),
  (1975, 'PHYSICS', 'PETER', 'SWEDEN' 'SCIENTIST'),
  
SELECT *
FROM NOBEL_WIN
WHERE SUBJECT NOT LIKE  'P%';

