CREATE TABLE IF NOT EXISTS STUDENT (
    ROLL_NO TEXT PRIMARY KEY,
    NAME TEXT NOT NULL,
    AGE INTEGER
    );

INSERT INTO STUDENTS (ROLL_NO, NAME, ADRESS, PHONE, AGE) VALUES
 ('1', 'RAM', 'DELHI', '*****', 18),
 ('2', 'RAMESH', 'GURGADON', '*****', 18),
 ('3', 'SUJIT', 'ROHTAK', '*****', 20),
 ('4', 'SURESH', 'DELHI', '*****', 18),
 ('5', 'AMAN', 'ROHTAK', '*****', 20),
 ('6', 'HARASH', 'GURGADON', '*****', 18);


 SELECT * FORM Salesman;

 SELECT * FFOROM STUDENT;

 SELECT * FROM STUDENT WHERE AGE  = 18 AND ADRESS = 'DELHI';

 SELECT * FORM STUDENT WHERE AGE  = 18 AND NAME  = 'RAM';

 SELECT * FROM STUDENT WHERE NAME = 'RAM' OR NAME = 'SUJIT';

 SELECT * FROM STUDENT WHERE NAME = 'RAM' OR AGE = 20;

 SELECT * FROM STUDENT WHERE AGE = 18 AND (NAME = 'RAM' OR NAME = 'RAMESH');

